---
abstract: "Format number to a mixture of numbers and words (e.g. \"12,3 juta\")"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ID-Number-Format-MixWithWords
requires:
  Data::Clone: 0
  Exporter::Lite: 0
  Lingua::Base::Number::Format::MixWithWords: 0
  Lingua::EN::Number::Format::MixWithWords: 0
  Math::Round: 0
  Number::Format: 0
  Package::Rename: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Lingua-ID-Number-Format-MixWithWords/
  repository: http://github.com/sharyanto/Lingua-ID-Number-Format-MixWithWords
version: 0.05
